version: "2"
linters:
    default: standard
    enable:
        - sloglint
        - gocritic
        - goconst
        - funcorder
        - usestdlibvars

formatters:
    enable:
        - gofmt
        - gofumpt
