pipeline {
    agent {
        label 'linux'
    }
    tools {
        go '1.24'
        generic 'golangci-lint'
    }
    environment {
        HOST_GOARCH = sh(script: 'go env GOARCH', returnStdout: true).trim()
        PUBLISH_DIR = "${env.WORKSPACE}/publish/${env.HOST_GOARCH}"
    }
    options {
        buildDiscarder logRotator(numToKeepStr: '5')
        checkoutToSubdirectory 'src'
        ansiColor('xterm')
    }
    stages {
        stage('check') {
            steps {
                dir('src') {
                    sh 'golangci-lint run'
                }
            }
        }
        stage('build') {
            steps {
                dir('src') {
                    sh 'mkdir -p ${PUBLISH_DIR}'
                    sh 'cp ngx-dnsallow.sample.yaml ${PUBLISH_DIR}/ngx-dnsallow.yaml'
                    sh 'go build -o ${PUBLISH_DIR}/ngx-dnsallow'
                }
                dir(env.PUBLISH_DIR) {
                    zip zipFile:"${env.PUBLISH_DIR}/ngx-dnsallow-${env.HOST_GOARCH}.zip"
                    fingerprint "*"
                    archiveArtifacts artifacts: '*.zip'
                }
            }
        }
    }
    post {
        success {
            sh 'rm -rf publish/'
            dir('src') {
                sh 'git clean -xdf'
            }
        }
    }
}
