pipeline {
    agent {
        label 'linux'
    }
    tools {
        go '1.24'
    }
    options {
        buildDiscarder logRotator(numToKeepStr: '5')
        checkoutToSubdirectory 'src'
    }
    stages {
        stage('build') {
            steps {
                dir('src') {
                    sh 'go build'
                }
            }
        }
    }
    post {
        success {
            dir('src') {
                sh 'git clean -xdf'
            }
        }
    }
}
